### ISSUE TITLE
Latex-Emacs

### ISSUE THREAD

**Issue by rbarsotti** [arademaker/LP-2015.2#100]
http://www.gnu.org/software/auctex/manual/auctex.pdf

Tutorial para quem quiser fazer o relatório final em LaTeX usando o própio emacs como editor de texto, e assim pode mesclar com alguns pedaços de códigos também

**Comment by arademaker** [comment]
mandei para a lista este info e também algumas outras referências, isto certamente não é um issue para ser tratado, a lista é o melhor lugar para esta troca de informações.
