### ISSUE TITLE
Symbolic Differentiation

### ISSUE THREAD

**Issue by arademaker** [arademaker/LP-2015.2#12]
Vide https://goo.gl/2FDbmt

Implementar adaptando para Common Lisp as rotinas básicas de derivação apresentadas na seção. Para isso, dentro do diretório ```sicp```crie um novo arquivo chamado ```deriv.lisp```. 

Em seguida, implementar exercícios 2.56 e 2.57. 

Note que esta tarefa pode ser feita por mais de um aluno sync seus repositórios antes de submeter o pull request final para mim. Ou podem submeter pull requests intermediários para mim.

**Comment by leomcamilo** [comment]
Implementação da rotina básica feita. Só lembrar pro pessoal que está aberta a melhoras e a definição da função pair?. 
Além de faltar a conclusão dos exercícios 2.56 e 2.57.

**Comment by arademaker** [comment]
Vide ffb00a9

**Comment by arademaker** [comment]
Vide b463f12 que trata da exponenciação.

**Comment by rafaelbetatester** [comment]
Professor, eu e o Caio criamos um deriv-2, que acabou aparecendo a ideia quando estávamos resolvendo o exercício 2.57. O Caio sugeriu tentarmos usar algumas Funções de Alta Ordem, e nós gostamos do resultado, seria interessante fazer um Pull Request?

**Comment by arademaker** [comment]
Sem eu ver, não tenho como responder. Mas sim, podem fazer um pull request. Mas lembrem de atualizar seus repos a partir do meu antes de novas modificações e submissões de pull requests.

**Comment by arademaker** [comment]
este seu comentário deveria ficar no issue, não no comentário do commit particular.

**Comment by arademaker** [comment]
@rafaelbetatester escreveu para mim:

Em relação ao código da deriv.lisp para o exercício 2.57:

O exercício pede para receber entradas do tipo 

```
(deriv '(+ x x x x x x) 'x)
```

Inicialmente trocamos a solução que usávamos addend, augend e make-sum
por (para somar derivadas):

```
((sum? exp)
    (cons '+ (mapcar 'derivada-2 (cdr exp))))
```

A ideia aqui foi colocar um sinal de mais no inicio da lista, e aplicar
a derivada em todos os elementos. Então

```
(deriv '(+ a1 a2 a3 ... an)) = (+ (deriv a1) (deriv a2) .... (deriv an))
```

O produto foi mais difícil de se fazer, e trocamos por:

```
((product? exp)
  (append '(+) (union (cdr exp)
                      (mapcar 'derivada-2 (cdr exp)))))))
```    

Onde acabamos precisando definir as funções union e change que acabaram
tendo um viés muito imperativo, eu não consegui pensar em uma solução
funcional elegante ainda.

```
(defun union (a b)
  (if (null a) nil
      (loop for x from 0 to (1- (length b))
	 collect (change a b x))))	

(defun change (a b x)
  (setq lista  (copy-list a))
  (setf (nth x lista) (nth x b)) 
  (append '(*) lista))
```

A ideia aqui foi colocar 

```
(deriv '(* a1 a2 a3 a4 ... an)) =
 (+ (* (deriv a1) a2 ...an) (* a1 (deriv a2) ... an) ...))
```

Gostaria de saber se é interessante fazer o pull dessa versão, ou se
seria necessário melhorar as funções union e change antes?

**Comment by arademaker** [comment]
Sobre as idéias do Rafael, vide que em https://goo.gl/Wyjxqp a sugestão é 

> Try to do this by changing only the representation for sums and products, without changing the deriv procedure at all. For example, the addend of a sum would be the first term, and the augend would be the sum of the rest of the terms.

**Comment by arademaker** [comment]
fica como exercício pensar como resolver o problema

```
cl-user> (reduce (lambda (x y) `(+ ,x ,y)) '(+ a b c))
(+ (+ (+ + a) b) c)
```

Possivelmente usandos os argumentos adicionais que ```reduce``` aceita.

**Comment by arademaker** [comment]
Já resolvemos em sala mesmo:

```
(reduce (lambda (x y) `(+ ,x ,y)) (cdr '(+ a b c)))
````
