### ISSUE TITLE
range e range-1

### ISSUE THREAD

**Issue by arademaker** [arademaker/LP-2015.2#16]
1. implementar o comportamento mais semelhante possível de range de python.
2. completar range-1 para funcionar como o esperado.

Vide https://docs.python.org/2/library/functions.html#range

**Comment by talesrands** [comment]
Eu e o Rafael Rodrigues enviamos uma tentativa de implementação do Range (estilo Python).

**Comment by arademaker** [comment]
Várias alternativas foram apresentadas. Cada uma tem suas vantagens e desvantagens. O uso de ```&rest``` parece interessante, mas torna a interface da função mais obscura para os usuários e para tools como o slime.  Acho que o exercício foi interessante mas a lição é que cada linguagem acaba tendo uma característica particular que sugere abordagens diferentes para os mesmos problemas.
