### ISSUE TITLE
Mudando alist para hastable na implementação de Eliza

### ISSUE THREAD

**Issue by kalinest** [arademaker/LP-2015.2#55]
Criei um issue para discutir uma possível solução

**Comment by kalinest** [comment]
Achei um exemplo que usa hashtable para associar uma chave para um valor, não serve para o caso do eliza mas ja é uma base de pensamento

(defparameter *my-hash* (make-hash-table))

(setf (gethash 'first-key *my-hash*) 'one)

(defun print-hash-entry (key value)
  (format t "The value associated with the key ~S is ~S~%"))

(maphash #'print-hash-entry *my-hash*)

Ainda há o que discutir em sala.

**Comment by arademaker** [comment]
discussão em sala.
