### ISSUE TITLE
Exercício 5.10 do paip

### ISSUE THREAD

**Issue by kalinest** [arademaker/LP-2015.2#56]
A questão pergunta qual o problema com simple-qual e sugere testar (simple-equal '() '(nil . nil).

Definindo simple-equal:

```
(defun simple-equal (x y)
	   (or (eql x y)
	       (and (listp x) (listp y)
		    (simple-equal (first x) (first y))
		    (simple-equal (rest x) (rest y)))))
```

O problema da função é que ela não testa se x e y são átomos para poder associar, por isso 

```
(simple-equal '() '(nil . nil)   => T
```

Redefinindo simple-equal para testar x e y átomos temos a função já apresentada na seção 5.2

```
(defun simple-equal (x y)
	   (if (or (atom x) (atom y))
	       (eql x y)
	       (and (simple-equal (first x) (first y))
		    (simple-equal (rest x) (rest y)))))
```

Logo, ```(simple-equal '() '(nil . nil)``` devolve ```NIL```, pois x e y não são átomos.

**Comment by arademaker** [comment]
ok resolvido
