### ISSUE TITLE
adicionar tabela de símbolos do pattern matching

### ISSUE THREAD

**Issue by rkatz36368** [arademaker/LP-2015.2#75]
Apos a ultima atualização, o eliza nao esta dando resposta.  
vejo o resultado que estavamos obtendo.
```
eliza [1] > oi

eliza [2] > ola

eliza [3] > 
```

acho que a eliza quer umas ferias....

**Comment by arademaker** [comment]
completar tabela dos simbolos das funcoes auxiliares para pattern matching. Vide sec 6.2

**Comment by caioramalhofgv** [comment]
Tabela adicionada.

**Comment by arademaker** [comment]
O commit d046bf não resolve totalmente o problema. Vou fechar este issue que era apenas para colocar a tabela, mas vou abrir outro para criar testes do pattern matching.
