### ISSUE TITLE
Exercício 6.1

### ISSUE THREAD

**Issue by kalinest** [arademaker/LP-2015.2#76]
Mudando as regras do ELIZA para torná-lo mais simples de ler criando duas funções para abreviar o pat-match.

>(defun pat-match-abbrev (symbol expansion)
	   (setf (get symbol 'expand-pat-match-abbrev)
	       (expand-pat-match-abbrev expansion)))

>(defun expand-pat-match-abbrev (pat)
	   (cond ((and (symbolp pat) (get pat 'expand-pat-match-abbrev)))
		 ((atom pat) pat)
		 (t (cons (expand-pat-match-abbrev (first pat))
			  (expand-pat-match-abbrev (rest pat))))))

Fica claro quando testamos que o programa fica mais limpo

>  (pat-match-abbrev '?x* '(?* ?x))
(?* ?X)

Apenas mais uma maneira de deixar o código mais limpo e legível.

**Comment by arademaker** [comment]
Acho que aqui o autor esperava mais do que simplesmente esta vaga discussão. Apenas depois de atualizar todas as regras do Eliza inglês podemos fazer uma avaliação de como as abreviações ajudaram na legibilidade das regras. Vide commit 3024ec076fbe91f8b768c8d6c6228e61341059a4
